/* Ghana NCF <-> ISO/IEC 27002:2022 control mappings.
   Single dataset shared by the dashboard, mapping and gap-analysis pages so their figures always agree. */
const mappings = [
    { ncf: "Cybersecurity governance structure", domain: "Governance & Leadership", iso: "5.1 Policies for information security", theme: "Organizational", alignment: "strong" },
    { ncf: "National cybersecurity strategy", domain: "Governance & Leadership", iso: "5.2 Information security roles", theme: "Organizational", alignment: "strong" },
    { ncf: "Roles and responsibilities", domain: "Governance & Leadership", iso: "5.3 Segregation of duties", theme: "Organizational", alignment: "strong" },
    { ncf: "Stakeholder coordination", domain: "Governance & Leadership", iso: "5.4 Management responsibilities", theme: "Organizational", alignment: "moderate" },
    { ncf: "Resource allocation", domain: "Governance & Leadership", iso: "5.5 Contact with authorities", theme: "Organizational", alignment: "moderate" },
    { ncf: "Performance monitoring", domain: "Governance & Leadership", iso: "5.35 Independent review", theme: "Organizational", alignment: "strong" },
    { ncf: "Risk management framework", domain: "Governance & Leadership", iso: "5.7 Threat intelligence", theme: "Organizational", alignment: "strong" },
    { ncf: "Continuous improvement", domain: "Governance & Leadership", iso: "5.36 Compliance with policies", theme: "Organizational", alignment: "moderate" },
    { ncf: "Data protection legislation", domain: "Legal & Regulatory", iso: "5.34 Privacy and PII protection", theme: "Organizational", alignment: "strong" },
    { ncf: "Cybercrime legislation", domain: "Legal & Regulatory", iso: "5.6 Contact with special interest groups", theme: "Organizational", alignment: "partial" },
    { ncf: "Electronic transactions act", domain: "Legal & Regulatory", iso: "5.10 Acceptable use of information", theme: "Organizational", alignment: "moderate" },
    { ncf: "Regulatory compliance monitoring", domain: "Legal & Regulatory", iso: "5.35 Independent review", theme: "Organizational", alignment: "strong" },
    { ncf: "Legal frameworks for digital evidence", domain: "Legal & Regulatory", iso: "5.28 Collection of evidence", theme: "Organizational", alignment: "strong" },
    { ncf: "Consumer protection in cyberspace", domain: "Legal & Regulatory", iso: "5.31 Legal requirements", theme: "Organizational", alignment: "moderate" },
    { ncf: "National CERT/CSIRT establishment", domain: "Incident Response", iso: "5.24 Incident management planning", theme: "Organizational", alignment: "strong" },
    { ncf: "Incident reporting mechanisms", domain: "Incident Response", iso: "6.8 Information security event reporting", theme: "People", alignment: "strong" },
    { ncf: "Incident response procedures", domain: "Incident Response", iso: "5.26 Response to incidents", theme: "Organizational", alignment: "strong" },
    { ncf: "Threat intelligence sharing", domain: "Incident Response", iso: "5.7 Threat intelligence", theme: "Organizational", alignment: "strong" },
    { ncf: "Post-incident analysis", domain: "Incident Response", iso: "5.27 Learning from incidents", theme: "Organizational", alignment: "strong" },
    { ncf: "Crisis communication", domain: "Incident Response", iso: "5.25 Assessment of incidents", theme: "Organizational", alignment: "moderate" },
    { ncf: "Cyber drills and exercises", domain: "Incident Response", iso: "5.29 ICT readiness for continuity", theme: "Organizational", alignment: "moderate" },
    { ncf: "CII identification", domain: "Critical Infrastructure", iso: "5.9 Inventory of information", theme: "Organizational", alignment: "moderate" },
    { ncf: "CII protection standards", domain: "Critical Infrastructure", iso: "8.9 Configuration management", theme: "Technological", alignment: "partial" },
    { ncf: "Sector-specific guidelines", domain: "Critical Infrastructure", iso: "5.8 Information security in project mgmt", theme: "Organizational", alignment: "partial" },
    { ncf: "Resilience requirements", domain: "Critical Infrastructure", iso: "5.30 ICT readiness for continuity", theme: "Organizational", alignment: "strong" },
    { ncf: "Supply chain security", domain: "Critical Infrastructure", iso: "5.21 Managing ICT supply chain", theme: "Organizational", alignment: "strong" },
    { ncf: "Cybersecurity awareness programs", domain: "Capacity Building", iso: "6.3 Information security awareness", theme: "People", alignment: "strong" },
    { ncf: "Professional development", domain: "Capacity Building", iso: "6.6 Confidentiality agreements", theme: "People", alignment: "partial" },
    { ncf: "Academic curriculum integration", domain: "Capacity Building", iso: "6.3 Information security awareness", theme: "People", alignment: "moderate" },
    { ncf: "Cybersecurity research initiatives", domain: "Capacity Building", iso: "5.7 Threat intelligence", theme: "Organizational", alignment: "partial" },
    { ncf: "Public awareness campaigns", domain: "Capacity Building", iso: "6.3 Information security awareness", theme: "People", alignment: "moderate" },
    { ncf: "Skills gap assessment", domain: "Capacity Building", iso: "6.2 Terms and conditions", theme: "People", alignment: "partial" },
    { ncf: "International treaty participation", domain: "International Cooperation", iso: "5.6 Contact with special interest groups", theme: "Organizational", alignment: "partial" },
    { ncf: "Bilateral cybersecurity agreements", domain: "International Cooperation", iso: "5.5 Contact with authorities", theme: "Organizational", alignment: "moderate" },
    { ncf: "Information sharing with partners", domain: "International Cooperation", iso: "5.14 Information transfer", theme: "Organizational", alignment: "moderate" },
    { ncf: "Participation in global forums", domain: "International Cooperation", iso: "5.6 Contact with special interest groups", theme: "Organizational", alignment: "partial" },
    { ncf: "Cross-border incident coordination", domain: "International Cooperation", iso: "5.5 Contact with authorities", theme: "Organizational", alignment: "moderate" },
    { ncf: "Technology transfer programs", domain: "International Cooperation", iso: "5.23 Cloud services security", theme: "Organizational", alignment: "partial" },
    { ncf: "Regional capacity building support", domain: "International Cooperation", iso: "6.3 Information security awareness", theme: "People", alignment: "partial" },
    { ncf: "Vulnerability disclosure policy", domain: "Incident Response", iso: "8.8 Management of technical vulnerabilities", theme: "Technological", alignment: "strong" },
    { ncf: "Security audit requirements", domain: "Governance & Leadership", iso: "5.35 Independent review", theme: "Organizational", alignment: "strong" },
    { ncf: "Access control policy", domain: "Critical Infrastructure", iso: "8.3 Access restriction", theme: "Technological", alignment: "strong" },
    { ncf: "Encryption standards", domain: "Critical Infrastructure", iso: "8.24 Use of cryptography", theme: "Technological", alignment: "strong" },
    { ncf: "Network security monitoring", domain: "Incident Response", iso: "8.16 Monitoring activities", theme: "Technological", alignment: "strong" },
    { ncf: "Cloud security guidelines", domain: "Critical Infrastructure", iso: "5.23 Cloud services security", theme: "Organizational", alignment: "moderate" },
    { ncf: "Mobile device security", domain: "Critical Infrastructure", iso: "8.1 User endpoint devices", theme: "Technological", alignment: "moderate" },
    { ncf: "Security testing requirements", domain: "Governance & Leadership", iso: "8.34 Protection during audit testing", theme: "Technological", alignment: "moderate" },
];
window.GH_MAPPINGS = mappings;
